{% set name = "hijridate" %}
{% set version = "2.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afe4644c4d1fe3cfd2aa3c28bfa660405c12e5ba53249ba942ec68c7bb216e00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - python >={{ python_min }}

test:
  imports:
    - hijridate
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/dralshehri/hijridate
  license: MIT
  license_file: LICENSE
  summary: "Accurate Hijri-Gregorian dates converter based on Umm al-Qura calendar"
  description: >-
    HijriDate is a Python package for converting between Hijri and Gregorian dates using the Umm al-Qura calendar. The package has been thoroughly verified and tested against original references to ensure its accuracy and reliability. It has an intuitive design, allows rich comparison and basic formatting of Hijri dates,
    and is optimized for performance.
  doc_url: https://hijridate.readthedocs.io/

extra:
  recipe-maintainers:
    - dralshehri
