{% set name = "hijridate" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b47f0b2e5333d5d898c6f3472f5cee4a3f045c82d69c073c7a026f5a7aec5821

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - hijridate
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dralshehri/hijridate
  summary: Accurate Hijri-Gregorian dates converter based on the Umm al-Qura calendar
  license: MIT
  license_file: LICENSE
  doc_url: https://hijridate.readthedocs.io/

extra:
  recipe-maintainers:
    - dralshehri
